version: '2'

services:
  sabnzbd:
    #build:
      #context: ./sabnzbd
      #dockerfile: Dockerfile
      #image: lsioarmhf/sabnzbd:latest
    image: stiles/sabnzbd_image:latest
    container_name: sabnzbd_container_compose
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    dns:
      - '1.1.1.1'
      - '8.8.8.8'
    ports:
      - '9090:9090'
      - '8080:8080'
      - '563:563'
      - '443:443'
    volumes:
      - "/home/brettsalemink/development/Docker/docker-mediacenter-armhf/sabnzbd/config:/config"
      - "/home/brettsalemink/development/Docker/docker-mediacenter-armhf/sabnzbd/scripts:/scripts"
      - "/downloads:/downloads"
      - "/downloads/incomplete:/downloads/incomplete"
      - "/media/samba_share:/media/samba_share"  
    network_mode: "host"

  couchpotato:
    image: lsioarmhf/couchpotato:latest
    container_name: couchpotato_container_compose
    restart: always
    ports:
      - '5050:5050'
    volumes:
      - "/home/brettsalemink/development/Docker/docker-mediacenter-armhf/couchpotato/config:/config"
      - "/downloads:/downloads"
      - "/downloads/completed/movies:/downloads/completed/movies"
      - "/media/samba_share/Video/Movies:/media/samba_share/Video/Movies" 
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    network_mode: 'host'
    depends_on:
      - sabnzbd

  sonarr:
    image: lsioarmhf/sonarr:latest
    container_name: sonarr_container_compose
    restart: always
    ports:
      - '8989:8989'
    volumes:
      - "/home/brettsalemink/development/Docker/docker-mediacenter-armhf/sonarr/config:/config"
      - "/downloads:/downloads"
      - "/media/samba_share/Video/TV-Shows:/media/samba_share/Video/TV-Shows"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    network_mode: 'host'
    depends_on:
      - sabnzbd
      - couchpotato

  headphones:
    image: lsioarmhf/headphones:latest
    container_name: headphones_container_compose
    restart: always
    ports:
      - '8181:8181'
    volumes:
      - "/home/brettsalemink/development/Docker/docker-mediacenter-armhf/headphones/config:/config"
      - "/downloads:/downloads"
      - "/downloads/completed/audio:/downloads/completed/audio"
      - "/media/samba_share:/media/samba_share"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    network_mode: "host"
    depends_on: 
      - sabnzbd
      - couchpotato
      - sonarr

  htpcmanager:
    image: lsioarmhf/htpcmanager:latest
    container_name: htpcmanager_container_compose
    restart: always
    ports:
      - '8085:8085'
    volumes:
      - "/home/brettsalemink/development/Docker/docker-mediacenter-armhf/htpcmanager/config:/config"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    network_mode: "host"
    depends_on:
      - sabnzbd
      - couchpotato
      - sonarr
      - headphones
